<a href="https://colab.research.google.com/github/Ronast10/Concepts-and-Technologies-of-AI.-WorkSheet-/blob/main/Ronast_Acharya_2417737_Workshop_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ronast Acharya 2417737
#WorkSheet-3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

Warm Up Exercises:
1. Sorting and Subsetting:
Complete all following Task:
• Dataset for the Task: "titanic.csv"
Following task is common for all the problem:
1. Load the provided dataset and import in pandas DataFrame.
2. Check info of the DataFrame and identify following:

In [ ]:
import pandas as pd

# Load the dataset
df=pd.read_csv('/content/drive/MyDrive/5CS037/Dataset/Titanic-Dataset.csv')

In [ ]:
print("\nDataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [ ]:
# Creating a DataFrame called fare containing only the Fare column
fare = df[['Fare']]

# Display
fare.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [ ]:


# Creating a DataFrame called class_age containing only the Pclass and Age columns
class_age = df[['Pclass', 'Age']]

# Display
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [ ]:
# Creating a DataFrame called survived_gender containing the Survived and Sex columns
survived_gender = df[['Survived', 'Sex']]

# Display
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:

Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [ ]:
# Filtering the dataset for passengers with Fare > 100
fare_gt_100 = df[df['Fare'] > 100]

# Display
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [ ]:
# Filtering the dataset for passengers with Pclass = 1
first_class = df[df['Pclass'] == 1]

# Display

first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [ ]:
# Filtering the dataset for female passengers under 18
female_under_18 = df[(df['Age'] < 18) & (df['Sex'] == 'female')]

# Display
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.

In [ ]:
# Filtering the dataset for passengers whose Embarked is "C" or "S"
embarked_c_or_s = df[df['Embarked'].isin(['C', 'S'])]

# Display
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [ ]:
# Filtering the dataset for passengers whose Pclass is in [1, 2]
first_second_class = df[df['Pclass'].isin([1, 2])]

# Display
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.2 Exploratory Data Analysis Practice Exercise - 1

Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [ ]:
# Filling missing values in the Age column with the median age
df['Age'] = df['Age'].fillna(df['Age'].median())
# Adding a new column 'fare_per_year' as Fare divided by Age
df['fare_per_year'] = df['Fare'] / df['Age']
# Subset rows where fare_per_year is greater than 5
high_fare_age = df[df['fare_per_year'] > 5]
# Sorting by fare_per_year in descending order
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending=False)
# Sorting by fare_per_year in descending order
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending=False)
# Selecting only the Name and fare_per_year columns
result = high_fare_age_srt[['Name', 'fare_per_year']]

# Display
result.head()

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [ ]:
# Adding a new column 'fare_per_class' as Fare divided by Pclass
df['fare_per_class'] = df['Fare'] / df['Pclass']
# Subset rows where the passenger is male and an adult
adult_males = df[(df['Sex'] == 'male') & (df['Age'] >= 18)]
# Sorting by fare_per_class in descending order
adult_males_srt = adult_males.sort_values(by='fare_per_class', ascending=False)
# Selecting the relevant columns
result = adult_males_srt[['Name', 'Age', 'fare_per_class']]

# Display
result.head()

                                   Name   Age  fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
438                   Fortune, Mr. Mark  64.0        263.0000
27       Fortune, Mr. Charles Alexander  19.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:

Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [ ]:
# Calculating the total fare across all passengers
total_fare = df['Fare'].sum()
# Total fare for first class
first_class_fare = df[df['Pclass'] == 1]['Fare'].sum()
# Total fare for second class
second_class_fare = df[df['Pclass'] == 2]['Fare'].sum()
# Total fare for third class
third_class_fare = df[df['Pclass'] == 3]['Fare'].sum()
# Combining the fare totals into a list
fare_totals = [first_class_fare, second_class_fare, third_class_fare]
# Calculating the percentage of total fare revenue for each class
fare_percentages = [(fare / total_fare) * 100 for fare in fare_totals]

# Display
fare_percentages

[63.349287718996564, 13.24962855496507, 23.401083726038365]

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?

To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.

In [ ]:
#Creating a new column 'age_group'
df['age_group'] = pd.cut(
    df['Age'],
    bins=[0, 18, 64, float('inf')],
    labels=['child', 'adult', 'senior']
)
#Calculating the total number of passengers
total_passengers = len(df)
#Counting the number of passengers in each age group
age_group_counts = df['age_group'].value_counts()
#Calculating the proportion of passengers in each age group
age_group_percentages = (age_group_counts / total_passengers) * 100
#Displaying the proportions as percentages
age_group_percentages

age_group
adult     83.164983
child     15.600449
senior     1.234568
Name: count, dtype: float64